require("my_config.treesitter")
require("my_config.telescope")
require("my_config.lsp")
require("my_config.snippets")
require("my_config.comment")
require("my_config.autopairs")
require("my_config.colorizer")
require("my_config.null-ls")
require("my_config.theme")
require("my_config.gitsigns")
require("my_config.git")

require("my_config.lualine")
-- require("my_config.bufferline")
-- require("my_config.nvim-tree")
-- require("my_config.alpha")
